// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateServices implements pgx.CopyFromSource.
type iteratorForCreateServices struct {
	rows                 []CreateServicesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateServices) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateServices) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Slug,
		r.rows[0].ProviderType,
		r.rows[0].IncidentsUrl,
		r.rows[0].ScheduleMaintenancesUrl,
		r.rows[0].ComponentsUrl,
	}, nil
}

func (r iteratorForCreateServices) Err() error {
	return nil
}

func (q *Queries) CreateServices(ctx context.Context, arg []CreateServicesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"services"}, []string{"name", "slug", "provider_type", "incidents_url", "schedule_maintenances_url", "components_url"}, &iteratorForCreateServices{rows: arg})
}
