// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_services.sql

package db

import (
	"context"
)

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, slug, provider_type, incidents_url, schedule_maintenances_url, components_url, created_at, updated_at, deleted_at FROM services
`

func (q *Queries) GetAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ProviderType,
			&i.IncidentsUrl,
			&i.ScheduleMaintenancesUrl,
			&i.ComponentsUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
