// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_services.sql

package db

type CreateServicesParams struct {
	Name                    string `db:"name"`
	Slug                    string `db:"slug"`
	ProviderType            string `db:"provider_type"`
	IncidentsUrl            string `db:"incidents_url"`
	ScheduleMaintenancesUrl string `db:"schedule_maintenances_url"`
	ComponentsUrl           string `db:"components_url"`
}
