// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Component struct {
	ID               int32              `db:"id"`
	Name             string             `db:"name"`
	ServiceID        int32              `db:"service_id"`
	ProviderID       string             `db:"provider_id"`
	ComponentGroupID pgtype.Int4        `db:"component_group_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
}

type ComponentGroup struct {
	ID         int32              `db:"id"`
	Name       string             `db:"name"`
	ServiceID  int32              `db:"service_id"`
	ProviderID string             `db:"provider_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at"`
}

type Incident struct {
	ID                int32              `db:"id"`
	Name              string             `db:"name"`
	Link              string             `db:"link"`
	ProviderImpact    pgtype.Text        `db:"provider_impact"`
	Impact            pgtype.Text        `db:"impact"`
	ServiceID         int32              `db:"service_id"`
	ProviderID        string             `db:"provider_id"`
	ProviderCreatedAt pgtype.Timestamptz `db:"provider_created_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at"`
}

type IncidentComponent struct {
	ID          int32              `db:"id"`
	IncidentID  int32              `db:"incident_id"`
	ComponentID int32              `db:"component_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at"`
}

type IncidentUpdate struct {
	ID             int32              `db:"id"`
	IncidentID     int32              `db:"incident_id"`
	Description    string             `db:"description"`
	ProviderStatus string             `db:"provider_status"`
	Status         string             `db:"status"`
	StatusTime     pgtype.Timestamptz `db:"status_time"`
	ProviderID     string             `db:"provider_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at"`
}

type Service struct {
	ID                      int32              `db:"id"`
	Name                    string             `db:"name"`
	Slug                    string             `db:"slug"`
	ProviderType            string             `db:"provider_type"`
	IncidentsUrl            string             `db:"incidents_url"`
	ScheduleMaintenancesUrl string             `db:"schedule_maintenances_url"`
	ComponentsUrl           string             `db:"components_url"`
	CreatedAt               pgtype.Timestamptz `db:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at"`
}
