- name: Twilio
  link: https://status.twilio.com
  should_scrap_website: false
  incident_url: https://status.twilio.com/api/v2/incidents.json
  schedule_maintenance_url: https://status.twilio.com/api/v2/scheduled-maintenances.json
  components_url: https://status.twilio.com/api/v2/components.json
  provider_type: atlassian

- name: Plivo
  link: https://status.plivo.com
  should_scrap_website: false
  incident_url: https://status.plivo.com/api/v2/incidents.json
  schedule_maintenance_url: https://status.plivo.com/api/v2/scheduled-maintenances.json
  components_url: https://status.plivo.com/api/v2/components.json
  provider_type: atlassian

- name: Squadcast
  link: https://status.squadcast.com
  should_scrap_website: false
  incident_url: https://status.squadcast.com
  schedule_maintenance_url: 
  components_url:
  provider_type: squadcast

