// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getServices = `-- name: GetServices :one
SELECT id, name, link, slug, provider_type, incident_url, schedule_maintenance_url, components_url, created_at, updated_at, deleted_at
FROM services
LIMIT 1
`

func (q *Queries) GetServices(ctx context.Context) (Service, error) {
	row := q.db.QueryRow(ctx, getServices)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.Slug,
		&i.ProviderType,
		&i.IncidentUrl,
		&i.ScheduleMaintenanceUrl,
		&i.ComponentsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
